import * as path from 'path';
import test from 'ava';
import {indexen} from './indexen';
import {defaultConfigurations} from './defaultConfigurations';

test('indexen', async (t) => {
    const directory = path.join(__dirname, '../src');
    const code = await indexen({
        ...defaultConfigurations,
        directory,
    });
    t.deepEqual(code.trim().split('\n'), [
        '// Generated by @nlib/indexen',
        'export * from \'./defaultConfigurations\';',
        'export * from \'./indexen\';',
        'export * from \'./parseIndexenCLIArgs\';',
        'export * from \'./types\';',
    ]);
});
