export * from '@nlib/global';
const _Buffer = Buffer; export {_Buffer as Buffer};
const _clearImmediate = clearImmediate; export {_clearImmediate as clearImmediate};
const _exports = exports; export {_exports as exports};
const _global = global; export {_global as global};
const _module = module; export {_module as module};
const _process = process; export {_process as process};
// const _queueMicrotask = queueMicrotask; export {_queueMicrotask as queueMicrotask};
const _require = require; export {_require as require};
const _setImmediate = setImmediate; export {_setImmediate as setImmediate};
// const _TextDecoder = TextDecoder; export {_TextDecoder as TextDecoder};
// const _TextEncoder = TextEncoder; export {_TextEncoder as TextEncoder};
